@startuml
participant Main
box Smooks Framework
participant Smooks
participant "edi:unparser"
participant StringSink
end box
autonumber

Main -> Smooks : ""filterSource(...)""
loop XML stream
    Smooks -> "edi:unparser": Event
    Smooks <-- "edi:unparser": Serialise to EDI
    Smooks -> StringSink: Write EDI
end
Smooks --> Main
Main -> StringSink: Read
StringSink --> Main: XML
@enduml