@startuml
participant Main
box Smooks Framework
participant Smooks
participant "csv:reader"
collections "Bean visitors"
participant "Bean Context"
participant "ftl:freemarker"
participant WriterSink
end box
autonumber

Main -> Smooks : ""createExecutionContext()""
Smooks -> "csv:reader"
create "Bean visitors"
"csv:reader" -> "Bean visitors": Create
Main -> Smooks : ""filterSource(...)""
Smooks -> "csv:reader": Input source
loop CSV stream
    Smooks <- "csv:reader": Event
    alt path(event) == ""person"" && isStartEvent(event)
        Smooks -> "Bean visitors": Event
        "Bean visitors" -> "Bean Context": Create ""java.util.Map"" named ""person""
    else path(event) == ""person/firstname"" && isEndEvent(event)
        Smooks -> "Bean visitors": Event
        "Bean visitors" -> "Bean Context": Bind event to new entry in ""person""
    else path(event) == ""person/lastname"" && isEndEvent(event)
        Smooks -> "Bean visitors": Event
        "Bean visitors" -> "Bean Context": Bind event to new entry in ""person""
    else path(event) == ""person/gender"" && isEndEvent(event)
        Smooks -> "Bean visitors": Event
        "Bean visitors" -> "Bean Context": Bind event to new entry in ""person""
    else path(event) == ""person/age"" && isEndEvent(event)
        Smooks -> "Bean visitors": Event
        "Bean visitors" -> "Bean Context": Bind event to new entry in ""person""
    else path(event) == ""person/country"" && isEndEvent(event)
        Smooks -> "Bean visitors": Event
        "Bean visitors" -> "Bean Context": Bind event to new entry in ""person""
    end
    alt path(event) == ""person"" or descendant
        Smooks -> "ftl:freemarker": Event
        alt ""person.gender"" == "male"
            "ftl:freemarker" --> Smooks: <male...>...</male>
        else
            "ftl:freemarker" --> Smooks: <female...>...</female>
        end
    end
    Smooks -> WriterSink: Write event as XML
end
Smooks --> Main
Main -> WriterSink: Read
WriterSink --> Main: XML
@enduml