@startuml
participant Main
box Smooks Framework
participant Smooks
participant "csv:reader"
participant WriterSink
end box
autonumber

Main -> Smooks : ""filterSource(...)""
Smooks -> "csv:reader": Input source
loop CSV stream
    Smooks <- "csv:reader": Event
    Smooks -> WriterSink: Write event as XML
end
Smooks --> Main
Main -> WriterSink: Read
WriterSink --> Main: XML
@enduml