@startuml
participant Main
box Smooks Framework
participant Smooks
participant "csv:reader"
collections "Bean visitors"
participant "Bean Context"
participant JavaSink
end box
autonumber

Main -> Smooks : ""createExecutionContext()""
Smooks -> "csv:reader"
create "Bean visitors"
"csv:reader" -> "Bean visitors": Create
Main -> Smooks : ""filterSource(...)""
Smooks -> "csv:reader": Input source
loop CSV stream
    Smooks <- "csv:reader": Event
    alt path(event) == #document && isStartEvent(event)
        Smooks -> "Bean visitors": Event
        "Bean visitors" -> "Bean Context": Create ""customerList"" bean
    else
        "Bean visitors" -> "Bean Context": Create ""Customer"" & add to ""customerList""
    end
end
Smooks --> Main
Main -> JavaSink: Get ""customerList""
JavaSink -> "Bean Context": Get ""customerList""
"Bean Context" --> JavaSink: ""customerList""
JavaSink --> Main: ""customerList""
@enduml