@startuml
participant Main
box Smooks Framework
participant Smooks
participant "dfdl:parser"
participant "dfdl:unparser"
participant Sink
end box
actor "Security team" order 1
autonumber

Main -> Smooks : ""filterSource(...)""
Smooks -> "dfdl:parser": Input source
loop NITF stream
    Smooks <- "dfdl:parser": Event
    alt path(event) == (""/NITF"" || descendant) && path(event) == ""//*[not(self::InvalidData)]""
        Smooks -> "dfdl:unparser": Event
        "dfdl:unparser" --> Smooks: Serialise to NITF
        Smooks -> Sink: Write NITF
        Sink -> Filesytem
    end
    alt path(event) == (""/NITF/InvalidData"" || descendant)
        Smooks -> "Dead letter channel": Write event as XML
    end
end
Smooks --> Main
"Security team" -> "Dead letter channel": Inspect
"Security team" <-- "Dead letter channel": XML document
@enduml