name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '/**/*.md'
      - '/**/*.puml'
      - '/**/*.png'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '/**/*.md'
      - '/**/*.puml'
      - '/**/*.png'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Build
        run: mvn install -B
