name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Build
        run: mvn install -B
  generate_uml_diagrams:
    if: github.repository == 'smooks/smooks-examples' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - uses: ts-graphviz/setup-graphviz@v1
      - run: curl -LJ https://github.com/plantuml/plantuml/releases/download/v1.2023.13/plantuml-1.2023.13.jar -o plantuml.jar
      - run: java -jar plantuml.jar -v -tpng -r **/**.puml -o docs/images
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: generate UML diagrams'
          push_options: --force
          file_pattern: '**/docs/images/*.png'
          disable_globbing: true
